/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: [".*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    /^unified.*/,
    /^rehype.*/,
    /^remark.*/,
    /^bail.*/,
    /^micromark.*/,
    /^mdast.*/,
    /^hast.*/,
    /^unist.*/,
    /^vfile.*/,
    /^character-entities.*/,
    "is-plain-obj",
    "trough",
    "fault",
    "decode-named-character-reference",
    "zwitch",
    "longest-streak",
    "trim-lines",
    "property-information",
    "html-void-elements",
    "space-separated-tokens",
    "comma-separated-tokens",
    "stringify-entities",
    "ccount",
  ],
};
